### ISSUE TITLE
Should output "cargo:rerun-if-env-changed=..." for all variables that affect compilation

### ISSUE THREAD

**Issue by glandium** [alexcrichton/cc-rs#318] opened 2018-05-16 08:06 UTC
Currently, if you have a build script that uses cc, and alter, one of, say, `CC`, `CXX`, `CFLAGS`, etc. nothing happens. Worse yet, cargo happily outputs warnings from a previous build with the old environment variables, making you think something was rebuilt when that's not the case.

**Comment by alexcrichton** [comment] 2018-05-16 14:12
I believe this is a duplicate of https://github.com/alexcrichton/cc-rs/issues/230, so closing

**Closed by alexcrichton** 2018-05-16 14:12 UTC
