### ISSUE TITLE
ToolFamily detected incorrectly on my macbook pro

### ISSUE THREAD

**Issue by mtak-** [alexcrichton/cc-rs#418] opened 2019-06-27 00:59 UTC
On my macos machine, `cc::Build::new()` always detects `c++` as the compiler which is really just a wrapper around apple clang. Because the name is `c++` it is detected as part of the Gnu family.

EDIT: Err - it detects `c++` as the compiler when building for `x86_64-apple-ios` (64-bit ios simulator). I was in a bit of a rush when I reported this issue.

**Comment by alexcrichton** [comment] 2019-06-27 08:43
I think this is a duplicate of https://github.com/alexcrichton/cc-rs/issues/408 so I'm going to close in favor of that.

**Closed by alexcrichton** 2019-06-27 08:43 UTC
