### ISSUE TITLE
Can't compile for android

### ISSUE THREAD

**Issue by Dispersia** [alexcrichton/cc-rs#427] opened 2019-08-03 19:22 UTC
I saw this issue: https://github.com/alexcrichton/cc-rs/issues/308 but I don't think another issue was ever created. I have tried going back to android-ndk-r16b where the `arm-linux-androideabi-clang` is installed, and have the .cargo/config pointing to it correctly, but I still get that it's missing.

 I also tried on NDK 20 to specify the linker I wanted it to use, and it still wants the `arm-linux-androideabi-clang` even if that's not what I told it to use as the last user on that thread posted.

 I'm trying to compile https://github.com/Dispersia/bounce using cargo-apk, if you want to reproduce it. I have OpenSSL set to the correct prebuilt android binaries.

 Is there any way to get this to build?
![image](https://user-images.githubusercontent.com/7254623/62416077-5b94da00-b5e9-11e9-8252-46c94be50678.png)

EDIT: I symlinked those files to the base NDK folder and just reference it there and it seems to be working under ndk 16b... Should it not use the cargo config full path to reference the executable? Is this a problem with cargo-apk then? I'm not sure which part of the build is calling this.

 Thanks!

**Comment by alexcrichton** [comment] 2019-08-05 15:10
Thanks for the report! I think this is largely a duplicate of https://github.com/alexcrichton/cc-rs/issues/82 since this crate doesn't read Cargo's configuration and otherwise there's not auto-detection to find the compiler and you'll need to specify it either via an env var or by augmenting PATH

**Closed by alexcrichton** 2019-08-05 15:10 UTC

**Comment by mad-de** [comment] 2019-09-13 08:04
> Thanks for the report! I think this is largely a duplicate of #82 since this crate doesn't read Cargo's configuration and otherwise there's not auto-detection to find the compiler and you'll need to specify it either via an env var or by augmenting PATH

Thanks for your work and help. Could you kindly give me your setup there? I tried various settings for ENV var and PATH for my android toolchain and I'm always getting the same or similar errors.

**Comment by Dispersia** [comment] 2019-09-13 14:03
Ya, the environment variables seem to be ignored, even if the build.rs says not to.

I personally fixed the cc-rs to use the toolchains I want, and use [patch] to override everyone to use that instead of the crates.io one. It works on Linux and wsl2, but can't get it working on windows due to linker errors.

**Comment by alexcrichton** [comment] 2019-09-16 14:26
The environment variables for selecting compilers and passing flags is [documented here](https://github.com/alexcrichton/cc-rs#external-configuration-via-environment-variables)
