### ISSUE TITLE
When compiling for target thumbv7em-none-eabi, wrong `ar` is called

### ISSUE THREAD

**Issue by Geobert** [alexcrichton/cc-rs#442] opened 2019-09-19 12:38 UTC
I have this:
```rust
cc::Build::new()
        .target("thumbv7em-none-eabi")
// many include() and define() calls
       .file("my_file.c")
       .compile("libmine.a");
}
```

and got this error:
```
AR_thumbv7em-none-eabi = None
AR_thumbv7em_none_eabi = None
TARGET_AR = None
AR = None
running: "ar" "crs" "C:\\Users\\Geob\\Dev\\efr32mg12-sys\\target\\debug\\build\\efr32mg12-sys-62c96ae52fc7f407\\out\\libgecko.a" "C:\\Users\\Geob\\Dev\\efr32mg12-sys\\target\\debug\\build\\efr32mg12-sys-62c96ae52fc7f407\\out\\lib/sdk/hardware/kit/common/bsp\\bsp_stk_leds.o"

--- stderr


error occurred: Failed to find tool. Is `ar` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)
```

I had to add:
```rust
env::set_var("AR", "arm-none-eabi-ar");
```

before `cc` call to make it work.

Is that expected behaviour?

**Comment by alexcrichton** [comment] 2019-09-19 13:33
Thanks for the report! I think this is a duplicate of https://github.com/alexcrichton/cc-rs/issues/330 so I'm going to close in favor of that

**Closed by alexcrichton** 2019-09-19 13:33 UTC

**Comment by Geobert** [comment] 2019-09-19 13:38
I really need to force myself to search in closed issue and not only opened one… thank you for your answer!
