### ISSUE TITLE
Don't rebuild c/cpp files that haven't changed since last build

### ISSUE THREAD

**Issue by cpearce** [alexcrichton/cc-rs#257] opened 2017-10-18 08:49 UTC
We're using cc-rs in [gecko-media](https://github.com/servo/gecko-media) and we've got enough files in our build now that a rebuild takes about a full minute now, which is pretty painful if you only changed one file. It would be awesome if cc-rs could automatically look in the target dir for previous builds and figure out what symbols haven't changed, and just relink the previous build's objects, rather than rebuilding every C/CPP file every single time.

**Comment by alexcrichton** [comment] 2017-10-18 14:04
Thanks for the report! I think this is a dupe of https://github.com/alexcrichton/cc-rs/issues/230 so I'm going to close in favor of that.

**Closed by alexcrichton** 2017-10-18 14:04 UTC

**Comment by cpearce** [comment] 2017-10-18 15:41
I'm not sure it is the same as #230 though. Unless I'm mistaken, the re-run-if directives tell Cargo when to rerun the build script. If a build script re-runs, it reruns in its entirety, and the entire crate gets rebuilt.

What I want to happen is if the entire build script re-runs for whatever reason, cc-rs checks timestamps on headers/objects or whatever, and only rebuilds C/CPP files that have changed since the last build.

#230 is about detecting whether we should re-run the build script. This bug is about reducing what's rebuilt when we do rerun the build script.

**Comment by alexcrichton** [comment] 2017-10-18 17:58
It's true yeah, but #230 is sort of a prerequisite regardless? 

I'd also imagine that if a C/C++ project is big enough to warrant features like this you'd probably want to use something like make/cmake? I'm not personally super keen on reimplementing a "worse make" ...
